version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo "BUILD JAVA TOMCAT APPLICATION"
      - echo Build started on `date`
      - cd java_tomcat_application
      - mvn clean package  # Assuming you are using Maven to build your WAR file
artifacts:
  files:
    - java_tomcat_application/target/*.war