dev:
  instance_type: t2.micro
  min_size: 1
  max_size: 2

test:
  instance_type: t2.micro
  min_size: 2
  max_size: 4

prod:
  instance_type: t2.micro
  min_size: 3
  max_size: 6

default:
  instance_type: t2.micro
  min_size: 1
  max_size: 2